#!/bin/bash
#SBATCH -p linlab
#SBATCH -N 1 -n REPLICANUMBER -c 2
#SBATCH -t 7-00:00:00
#SBATCH -J SYSTEMNAME1
#SBATCH -o runout.%j
#SBATCH -e runerr.%j
#SBATCH --export=ALL
#SBATCH --gres=gpu:t4:3

#SBATCH --mem-per-cpu=1G

export GMXLIB=/cluster/tufts/ylin12/tim/localGMXLIB
source /cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/bin/GMXRC.bash
export PLUMED_KERNEL=/cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/plumed/lib/libplumedKernel.so

module load gcc/7.3.0
module load cuda/10.2
module load openmpi/2.1.2
module load libmatheval

nvidia-smi -ac 5001,1590
mpiexec -np REPLICANUMBER gmx_mpi mdrun -v -ntomp 2 -nb gpu -plumed bemeta -multi REPLICANUMBER -replex 2500 -s start -deffnm prod
