#SBATCH -p linlab
#SBATCH -N 1 -c 1 -n 4
#SBATCH -J Initiate
#SBATCH -o runout.%j
#SBATCH -e runerr.%j
#SBATCH -t 7-00:00:00
#SBATCH --export=ALL

module load python/3.6.0
module load gcc/7.3.0
module load cuda/10.2
module load openmpi/2.1.2
module load libmatheval

source /cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/bin/GMXRC.bash
export PLUMED_KERNEL=/cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/plumed/lib/libplumedKernel.so
export GMXLIB=/cluster/tufts/ylin12/tim/localGMXLIB

sequence=SEQUENCETOCHANGE
seq_length=${#sequence}
num_replica=$((${seq_length} * 2 + 5))

for i in 1 2
do 
    cd 3em_npt/s${i}
    gmx_mpi grompp -f em2.mdp -c ion.gro -p cx_rsff2_tip3p.top -o em2.tpr &> grompp_em2.log
    mpirun -np 4 gmx_mpi mdrun -v -s em2.tpr -deffnm em2 &> mdrun_em2.log

    python check_trajectory.py --seq ${sequence} --gro em2.gro
    gmx_mpi grompp -v -f nvt1.mdp -c em2.gro -r em2.gro -p cx_rsff2_tip3p.top -o nvt1.tpr &> grompp_nvt1.log
    mpirun -np 4 gmx_mpi mdrun -v -s nvt1.tpr -deffnm nvt1 &> mdrun_nvt1.log
    
    python check_trajectory.py --seq ${sequence} --gro nvt1.gro
    gmx_mpi grompp -v -f npt1.mdp -c nvt1.gro -r nvt1.gro -p cx_rsff2_tip3p.top -o npt1.tpr &> grompp_npt1.log
    mpirun -np 4 gmx_mpi mdrun -v -s npt1.tpr -deffnm npt1 &> mdrun_npt1.log

    python check_trajectory.py --seq ${sequence} --gro npt1.gro
    gmx_mpi grompp -v -f nvt2.mdp -c npt1.gro -p cx_rsff2_tip3p.top -o nvt2.tpr &> grompp_nvt2.log
    mpirun -np 4 gmx_mpi mdrun -v -s nvt2.tpr -deffnm nvt2 &> mdrun_nvt2.log

    python check_trajectory.py --seq ${sequence} --gro nvt2.gro
    gmx_mpi grompp -v -f npt2.mdp -c nvt2.gro -p cx_rsff2_tip3p.top -o npt2.tpr &> grompp_npt2.log
    mpirun -np 4 gmx_mpi mdrun -v -s npt2.tpr -deffnm npt2 &> mdrun_npt2.log

    python check_trajectory.py --seq ${sequence} --gro npt2.gro

    cp npt2.gro ../../4bemeta/s${i}
    cp cx_rsff2_tip3p.top ../../4bemeta/s${i}

    cd ../../4bemeta/s${i}
    sed -i s/SYSTEMNAME/${sequence}${i}/ submit.job
    sed -i s/TASKNUMBER/${num_replica}/ submit.job
    for j in `seq 0 $(($numReplica - 1))`
    do
        gmx_mpi grompp -v -f mdrun.mdp -p cx_rsff2_tip3p.top -c npt2.gro -o start${j}.tpr &> grompp${j}.log
        gmx_mpi dump -s start${j}.tpr &> dump${j}.log
    done
    grep "fudge" dump*log &> fudge_check.txt

    python writeBemeta.py --gro npt.gro


    cd ../../

done
