#!/bin/bash
#SBATCH -p linlab
#SBATCH -N 1 -n TASKNUMBER -c 4
#SBATCH -J SYSTEMNAME
#SBATCH -o runout.%j
#SBATCH -e runerr.%j
#SBATCH -t 7-00:00:00
#SBATCH --export=ALL
#SBATCH --gres=gpu:t4:3
#SBATCH --mem-per-cpu=1G

module load openmpi/2.1.2
module load libmatheval
module load cuda/10.2
module load gcc/7.3.0

export GMXLIB=/cluster/tufts/ylin12/tim/localGMXLIB
export PLUMED_KERNEL=/cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/plumed/lib/libplumedKernel.so
source /cluster/tufts/ysl8/jovan/gromacs_linlab_avx2/bin/GMXRC.bash

nvidia-smi -ac 5001,1590
mpirun -np TASKNUMBER gmx_mpi mdrun -ntomp 4 -nb gpu -v -s start -deffnm prod -plumed bemeta -multi 15 -replex 2500 
python check_trajectory.py --seq SYSTEMNAME
